server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        # Apply JwtAuthenticationFilter globally except for excluded routes
        - JwtAuthenticationFilter
      routes:
        - id: SECURITY-SERVICE
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: SECURITY-SERVICE
                fallbackUri: forward:/securityServiceFallBack

        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/v1/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: BOOK-SERVICE
                fallbackUri: forward:/bookServiceFallBack

resilience4j:
  circuitbreaker:
    instances:
      SECURITY-SERVICE:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
      BOOK-SERVICE:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
